################################################################
# Global configuration
################################################################

global:
  checkNewVersion: true
  sendAnonymousUsage: false

################################################################
# EntryPoints configuration
################################################################

entryPoints:
  http:
    address: :80
    http:
      middlewares:
        - local_network@file
#      redirections:
#        entryPoint:
#          to: https

  https:
    address: ":443"
    http:
      tls: {}
      middlewares:
        - local_network@file

  web:
    address: ":1000"
    http:
      middlewares:
        - cloudflare@file
      tls:
        options: cloudflare@file
        domains:
          - main: "bitbaker.fr"
            sans:
              - "*.bitbaker.fr"

  plex:
    address: ":32400"
    http:
      tls: {}


################################################################
# Traefik logs configuration
################################################################

log:
  level: DEBUG


################################################################
# Access logs configuration
################################################################

accessLog: {}

################################################################
# API and dashboard configuration
################################################################

api:
  insecure: false
  dashboard: true

################################################################
# Ping configuration
################################################################

ping:
  manualRouting: true

################################################################
# Docker configuration backend
################################################################

providers:
  file:
    filename: "/etc/traefik/static_conf.yaml"
    watch: true

  docker:
    endpoint: "unix:///var/run/docker.sock"

    watch: true
    useBindPortIP: true
    exposedByDefault: false

    defaultRule: Host(`{{ normalize .Name }}.fridge`)

################################################################
# Metrics configuration
################################################################

metrics:
  prometheus:
    addServicesLabels: true
    addEntryPointsLabels: true
    manualRouting: true
