services:
  adguardhome:
    image: adguard/adguardhome:v0.107.62
    container_name: adguardhome
    volumes:
      - config:/opt/adguardhome/conf
    ports:
      - 53:53/tcp
      - 53:53/udp
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.adguard.loadBalancer.server.port=3000"
      - "traefik.http.routers.adguard-local.entrypoints=http,https"
      - "traefik.http.routers.adguard-local.rule=Host(`adguard.fridge.local`)"

volumes:
  config:

networks:
  traefik:
    name: traefik
    external: true
