services:
  cloudflared:  # aka Kitchen Sink
    image: cloudflare/cloudflared:2025.9.1
    container_name: cloudflared
    command: tunnel --no-autoupdate run --token $CLOUDFLARE_TOKEN
    environment:
      CLOUDFLARE_TOKEN: $CLOUDFLARE_TOKEN
    networks:
      - cloudflare
    restart: unless-stopped

networks:
  cloudflare:
    name: cloudflare
    external: false
