services:
  homeassistant:
    image: ghcr.io/linuxserver/homeassistant:2025.4.1
    container_name: homeassistant
    environment:
      - PUID=103
      - PGID=996
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - config:/config
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.homeassistant.loadBalancer.server.port=8123"
      - "traefik.http.routers.homeassistant-local.entrypoints=http,https"
      - "traefik.http.routers.homeassistant-local.rule=Host(`hass.fridge.local`)"
      - "traefik.http.routers.homeassistant.entrypoints=cloudflare"
      - "traefik.http.routers.homeassistant.rule=Host(`hass.bitbaker.fr`)"

  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:7.0.1
    container_name: ha-matter-server
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - matter-server-data:/data
    networks:
      - matter
    restart: unless-stopped

  matter-hub:
    image: ghcr.io/t0bst4r/home-assistant-matter-hub:3.0.0-alpha.81
    container_name: ha-matter-hub
    environment:
      - HAMH_HOME_ASSISTANT_URL=http://homeassistant:8123/
      - HAMH_HOME_ASSISTANT_ACCESS_TOKEN=${HA_ACCESS_TOKEN:-}
      - HAMH_LOG_LEVEL=info
      - HAMH_HTTP_PORT=8482
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - matter-hub-data:/data
    networks:
      - matter
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.ha-matter-hub.loadBalancer.server.port=8482"
      - "traefik.http.routers.ha-matter-hub-local.entrypoints=http,https"
      - "traefik.http.routers.ha-matter-hub-local.rule=Host(`matter.fridge.local`)"

volumes:
  config:
  matter-server-data:
  matter-hub-data:

networks:
  traefik:
    name: traefik
    external: true
