services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin:10.10.7
    container_name: jellyfin
    environment:
      - PUID=103
      - PGID=996
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
      - JELLYFIN_PublishedServerUrl=jellyfin.fridge.local
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - config:/config
      - freezer_media:/data
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 7359:7359/udp
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.jellyfin.loadBalancer.server.port=8096"
      - "traefik.http.routers.jellyfin-local.entrypoints=http,https"
      - "traefik.http.routers.jellyfin-local.rule=Host(`jellyfin.fridge.local`)"

volumes:
  config:
  freezer_media:
    external: true

networks:
  traefik:
    name: traefik
    external: true
