version: "3.8"

services:
  plex:
    image: ghcr.io/linuxserver/jellyfin:10.10.3
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=992
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /srv/pool/docker/jellyfin:/config
      - /srv/pool/plex:/data
    devices:
      - /dev/dri:/dev/dri
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.jellyfin.loadBalancer.server.port=8096"
      - "traefik.http.routers.jellyfin-local.entrypoints=http,https"
      - "traefik.http.routers.jellyfin-local.rule=Host(`jellyfin.fridge`)"

networks:
  traefik:
    name: traefik
    external: true
