services:
  mdns-repeater:
    image: ghcr.io/jdelker/docker-mdns-repeater:master
    network_mode: "host"
    privileged: true
    environment:
      INTERFACES: "${INTERFACES}"
      DOCKER_NETWORKS: "${DOCKER_NETWORKS}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
