version: "3.8"

services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    environment:
      - PUID=1000
      - PGID=992
      - VERSION=docker
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /srv/pool/docker/plex:/config
      - /srv/pool/plex:/data
    ports:
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.plex.loadBalancer.server.port=32400"
      - "traefik.http.routers.plex-local.entrypoints=http,https"
      - "traefik.http.routers.plex-local.rule=Host(`plex.fridge`)"

networks:
  traefik:
    name: traefik
    external: true
