services:
  plex:
    image: ghcr.io/linuxserver/plex:1.41.8
    container_name: plex
    environment:
      - PUID=103
      - PGID=996
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - config:/config
      - freezer_media:/data
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 32400:32400
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.plex.loadBalancer.server.port=32400"
      - "traefik.http.routers.plex-local.entrypoints=http,https"
      - "traefik.http.routers.plex-local.rule=Host(`plex.fridge.local`)"


volumes:
  config:
  freezer_media:
    external: true

networks:
  traefik:
    name: traefik
    external: true
