version: '3.8'

x-common:
  database:
    &db-environment
    # Do not remove the "&db-password" from the end of the line below, it is important
    # for Panel functionality.
    MYSQL_PASSWORD: &db-password "uSqYabWEHUg5iE8Di4FmeDkQxXxDcGqtBpW9G3kLCR6ek7j2aTLmGvHrGmQJzrYJqp5JuJv4QG5WJTz7"
    MYSQL_ROOT_PASSWORD: "yyfoi6uWpSfYMZwNnQk3PSFBwx5F8CnoecMQBv2ThanNgHARdb7juh898wQZJnLivkMqbxFFAaHz9mxo"
  
  panel:
    &panel-environment
    APP_URL: "http://pterodactyl.fridge"
    # A list of valid timezones can be found here: http://php.net/manual/en/timezones.php
    APP_TIMEZONE: "UTC"
    APP_SERVICE_AUTHOR: "admin@bitbaker.fr"

  mail:
    &mail-environment
    MAIL_FROM: "noreply@bitbaker.fr"
    MAIL_DRIVER: "smtp"
    MAIL_HOST: "mail"
    MAIL_PORT: "1025"
    MAIL_USERNAME: ""
    MAIL_PASSWORD: ""
    MAIL_ENCRYPTION: "true"

#
# ------------------------------------------------------------------------------------------
# DANGER ZONE BELOW
#
# The remainder of this file likely does not need to be changed. Please only make modifications
# below if you understand what you are doing.
#
services:
  database:
    image: library/mysql:8.0
    restart: always
    networks:
      - local
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "/srv/pool/docker/pterodactyl/database:/var/lib/mysql"
    environment:
      <<: *db-environment
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"

  cache:
    image: redis:alpine
    restart: always
    networks:
      - local

  panel:
    image: ghcr.io/pterodactyl/panel:v1.9.1
    restart: always
    networks:
      - local
      - traefik
    links:
      - database
      - cache
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/srv/pool/docker/pterodactyl/panel/var/:/app/var/"
      - "/srv/pool/docker/pterodactyl/panel/logs/:/app/storage/logs"
      - "/srv/pool/docker/pterodactyl/panel/nginx/:/etc/nginx/conf.d/"
    environment:
      <<: [*panel-environment, *mail-environment]
      DB_PASSWORD: *db-password
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "database"
      TRUSTED_PROXIES: "*"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.pterodactyl.loadBalancer.server.port=80"
      - "traefik.http.routers.pterodactyl-local.entrypoints=http,https"
      - "traefik.http.routers.pterodactyl-local.rule=Host(`pterodactyl.fridge`)"
      - "traefik.http.routers.pterodactyl.entrypoints=cloudflare"
      - "traefik.http.routers.pterodactyl.rule=Host(`pterodactyl.bitbaker.fr`)"

networks:
  local:
    external: false

  traefik:
    name: traefik
    external: true

  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
