version: '3.8'

services:
  wings:
    image: ghcr.io/pterodactyl/wings:v1.6.4
    restart: always
    networks:
      - traefik
      - wings0
    ports:
      - "2022:2022"
    tty: true
    environment:
      TZ: "UTC"
      WINGS_UID: 988
      WINGS_GID: 988
      WINGS_USERNAME: pterodactyl
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "/tmp/pterodactyl/:/tmp/pterodactyl/"
      - "/etc/ssl/certs:/etc/ssl/certs:ro"
      - "/srv/pool/docker/pterodactyl/wings/etc/:/etc/pterodactyl/"
      - "/srv/pool/docker/pterodactyl/wings/logs:/var/log/pterodactyl/"
      - "/srv/game_servers/:/srv/game_servers/"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.pterodactyl-wing.loadBalancer.server.port=443"
      - "traefik.http.routers.pterodactyl-wing-local.entrypoints=http,https"
      - "traefik.http.routers.pterodactyl-wing-local.rule=Host(`pterodactyl-wing.fridge`)"

networks:
  traefik:
    name: traefik
    external: true
  
  wings0:
    name: wings0
    driver: bridge
    ipam:
      config:
        - subnet: "10.2.0.0/16"
    driver_opts:
      com.docker.network.bridge.name: wings0
