services:
  searxng:
    image: searxng/searxng:2024.11.17-10d3af84b
    container_name: searxng
    environment:
      - SEARXNG_BASE_URL=https://search.bitbaker.fr/
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - config:/etc/searxng
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.searxng.loadBalancer.server.port=8080"
      - "traefik.http.routers.searxng-local.entrypoints=http,https"
      - "traefik.http.routers.searxng-local.rule=Host(`search.fridge.local`)"
      - "traefik.http.routers.searxng.entrypoints=cloudflare"
      - "traefik.http.routers.searxng.rule=Host(`search.bitbaker.fr`)"

volumes:
  config:

networks:
  traefik:
    name: traefik
    external: true
