services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.2.1
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - uptime-kuma-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.uptime-kuma.loadBalancer.server.port=3001"
      - "traefik.http.routers.uptime-kuma-local.entrypoints=http,https"
      - "traefik.http.routers.uptime-kuma-local.rule=Host(`status.fridge.local`)"
      - "traefik.http.routers.uptime-kuma.entrypoints=cloudflare"
      - "traefik.http.routers.uptime-kuma.rule=Host(`status.bitbaker.fr`)"
      - "traefik.http.routers.arcadia-status.entrypoints=cloudflare"
      - "traefik.http.routers.arcadia-status.rule=Host(`status.arcadia-mc.eu`)"

volumes:
  uptime-kuma-data:

networks:
  traefik:
    name: traefik
    external: true
