services:
  traefik:
    image: traefik:v2.11.20
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      - "1000:1000"
    networks:
      - traefik
      # - cloudflare
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    configs:
      - traefik:/etc/traefik/traefik.yaml
      - static-config:/etc/traefikstatic_conf.yaml
    restart: unless-stopped

configs:
  traefik:
    file: configs/traefik/traefik.yaml
  static-config:
    file: configs/traefik/static_conf.yaml

networks:
  traefik:
    name: traefik
    external: true

  # cloudflare:
  #   name: cloudflare
  #   external: true
