services:
  traefik:
    image: traefik:v3.3.4
    container_name: "traefik"
    #user: "103:996"
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - "80:80"
      - "443:443"
      - "1000:1000"
    networks:
      - traefik
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "cloudflare_certs:/etc/traefik/certs:ro"
    configs:
      - source: traefik.yaml
        target: /etc/traefik/traefik.yaml
      - source: static_config.yaml
        target: /etc/traefik/static_config.yaml
    restart: unless-stopped

volumes:
  cloudflare_certs:
    external: true

configs:
  traefik.yaml:
    content: |
      global:
        sendAnonymousUsage: false

      experimental:
        plugins:
          cloudflare:
            moduleName: github.com/agence-gaya/traefik-plugin-cloudflare
            version: v1.2.0

      entryPoints:
        http:
          address: ":80"
          http:
            middlewares:
              - local_network@file

        https:
          address: ":443"
          http:
            tls: {}
            middlewares:
              - local_network@file

        cloudflare:
          address: ":1000"
          http3: {}
          http:
            middlewares:
              - cloudflare@file
            tls:
              options: cloudflare@file
              domains:
                - main: "bitbaker.fr"
                  sans:
                    - "*.bitbaker.fr"

      serversTransport:
        insecureSkipVerify: true

      log:
        level: DEBUG

      accessLog: {}

      api:
        insecure: false
        dashboard: true

      ping:
        manualRouting: true

      tracing:
        serviceName: traefik
        otlp: {}

      providers:
        file:
          filename: "/etc/traefik/static_config.yaml"

        docker:
          endpoint: "unix:///var/run/docker.sock"
          watch: true
          useBindPortIP: true
          exposedByDefault: false
          defaultRule: "Host(`{{ normalize .Name }}.fridge.local`)"
          network: traefik

  static_config.yaml:
    content: |
      tls:
        certificates:
          - certFile: /etc/traefik/certs/bitbaker.com.pem
            keyFile: /etc/traefik/certs/bitbaker.com.key

        options:
          cloudflare:
            sniStrict: true
            minVersion: VersionTLS12
            curvePreferences:
              - x25519
              - CurveP256
              - CurveP384
            cipherSuites:
              - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
              - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
              - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
              - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
              - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
              - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
            clientAuth:
              caFiles:
                - /etc/traefik/certs/cloudflare-mTLS-ca.pem
              clientAuthType: RequireAndVerifyClientCert

      http:
        routers:
          api:
            rule: "Host(`traefik.fridge.local`)"
            service: api@internal
            entrypoints:
              - http
              - https

          ping:
            rule: "Host(`traefik.fridge.local`) && PathPrefix(`/ping`)"
            service: ping@internal
            entrypoints:
              - http
              - https

        middlewares:
          local_network:
            chain:
              middlewares:
                - local_ip_only
                - security-headers

          cloudflare:
            chain:
              middlewares:
                - cloudflare-proxy
                - rate-limit
                - security-headers

          local_ip_only:
            ipAllowList:
              sourceRange:
                - "192.168.1.0/24"
                - "127.0.0.1/32"
                - "172.0.0.0/8"

          security-headers:
            headers:
              referrerPolicy: "no-referrer"
              customFrameOptionsValue: "sameorigin"
              stsSeconds: 31536000
              stsIncludeSubdomains: true
              contentTypeNosniff: true
              hostsProxyHeaders:
                - "X-Forwarded-Host"

          cloudflare-proxy:
            plugin:
              cloudflare:
                overwriteRequestHeader: true

          rate-limit:
            rateLimit:
              average: 100
              burst: 200

networks:
  traefik:
    name: traefik
    external: true
