services:
  controller:
    image: ghcr.io/linuxserver/unifi-network-application:9.0.114
    container_name: unifi-controller
    environment:
      - PUID=103
      - PGID=996
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_HOST=db
      - MONGO_PORT=27017
      - MONGO_DBNAME=${MONGO_DBNAME:-unifi}
      - MONGO_AUTHSOURCE=admin
    ports:
      - 3478:3478/udp   # STUN
      - 10001:10001/udp # AP discovery
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - config:/config
    networks:
      - default
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.unifi.loadBalancer.server.port=8080"
      - "traefik.http.routers.unifi-local.entrypoints=http,https"
      - "traefik.http.routers.unifi-local.rule=Host(`unifi.fridge.local`)"
      - "traefik.http.services.unifi-guest-portal.loadBalancer.server.port=8880"
      - "traefik.http.routers.unifi-guest-portal-local.entrypoints=http,https"
      - "traefik.http.routers.unifi-guest-portal-local.rule=Host(`unifi-guest.fridge.local`)"

  db:
    image: mongo:8.0.4-noble
    container_name: unifi-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_PASSWORD}
      - MONGO_INITDB_USERNAME=${MONGO_INITDB_USERNAME}
      - MONGO_INITDB_PASSWORD=${MONGO_INITDB_PASSWORD}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_DBNAME=${MONGO_DBNAME:-unifi}
    volumes:
      - data:/data/db
    configs:
      - source: mongo-init-script.sh
        target: /docker-entrypoint-initdb.d/init-mongo.sh
        mode: "0775"
    networks:
      - default
    restart: unless-stopped

configs:
  mongo-init-script.sh:
    content: |
      #!/bin/bash

      mongosh <<EOF
      use admin
      db.auth("${MONGO_INITDB_USERNAME}", "${MONGO_INITDB_PASSWORD}")
      db.createUser({
        user: "${MONGO_USER}",
        pwd: "${MONGO_PASS}",
        roles: [
          { role: "dbOwner", db: "${MONGO_DBNAME}" },
          { role: "dbOwner", db: "${MONGO_DBNAME}_stat" }
        ]
      })
      EOF

volumes:
  data:
  config:

networks:
  default:
  traefik:
    name: traefik
    external: true
