version: "3.8"

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    command: --interval 30
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/pool/docker/watchtower/config.json:/config.json
    restart: unless-stopped
